steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/car-recognition-api:latest', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/car-recognition-api:latest']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'car-recognition-api'
  - '--image'
  - 'gcr.io/$PROJECT_ID/car-recognition-api:latest'
  - '--platform'
  - 'managed'
  - '--region'
  - 'europe-west1'
  - '--memory'
  - '2Gi'
  - '--cpu'
  - '1'
  - '--port'
  - '5000'
  - '--allow-unauthenticated'

images:
- 'gcr.io/$PROJECT_ID/car-recognition-api:latest'

timeout: 1800s