apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-recognition-api
  labels:
    app: car-recognition-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-recognition-api
  template:
    metadata:
      labels:
        app: car-recognition-api
    spec:
      containers:
      - name: car-recognition-api
        image: gcr.io/car-recognition-deep-learning/car-recognition-api:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
        - name: PORT
          value: "8080"
        - name: MODEL_DIR
          value: "/tmp/models/transfer"
        - name: CLOUD_STORAGE_BUCKET
          value: "car-recognition-models-europe"
        - name: CLOUD_STORAGE_MODEL_PATH
          value: "models/transfer"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 30
        volumeMounts:
        - name: model-cache
          mountPath: /tmp/models
      volumes:
      - name: model-cache
        emptyDir: {}
      # Use a service account with storage access
      serviceAccountName: car-recognition-service-account
---
apiVersion: v1
kind: Service
metadata:
  name: car-recognition-api
spec:
  selector:
    app: car-recognition-api
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: car-recognition-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: car-recognition-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70