apiVersion: v1
kind: ServiceAccount
metadata:
  name: car-recognition-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: storage-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: car-recognition-storage-binding
subjects:
- kind: ServiceAccount
  name: car-recognition-service-account
roleRef:
  kind: Role
  name: storage-reader
  apiGroup: rbac.authorization.k8s.io